const countries = [
  {
    id: "ASM",
    name: "American Samoa",
    flag: "https://flagcdn.com/as.svg",
    continent: "Oceania",
    capital: "Pago Pago",
    subregion: "Polynesia",
    area: 199,
    population: 55197,
  },
  {
    id: "PER",
    name: "Peru",
    flag: "https://flagcdn.com/pe.svg",
    continent: "Americas",
    capital: "Lima",
    subregion: "South America",
    area: 1285216,
    population: 32971846,
  },
  {
    id: "TON",
    name: "Tonga",
    flag: "https://flagcdn.com/to.svg",
    continent: "Oceania",
    capital: "Nuku'alofa",
    subregion: "Polynesia",
    area: 747,
    population: 105697,
  },
  {
    id: "MYT",
    name: "Mayotte",
    flag: "https://flagcdn.com/yt.svg",
    continent: "Africa",
    capital: "Mamoudzou",
    subregion: "Eastern Africa",
    area: 374,
    population: 226915,
  },
  {
    id: "PAN",
    name: "Panama",
    flag: "https://flagcdn.com/pa.svg",
    continent: "Americas",
    capital: "Panama City",
    subregion: "Central America",
    area: 75417,
    population: 4314768,
  },
  {
    id: "MDG",
    name: "Madagascar",
    flag: "https://flagcdn.com/mg.svg",
    continent: "Africa",
    capital: "Antananarivo",
    subregion: "Eastern Africa",
    area: 587041,
    population: 27691019,
  },
  {
    id: "BEL",
    name: "Belgium",
    flag: "https://flagcdn.com/be.svg",
    continent: "Europe",
    capital: "Brussels",
    subregion: "Western Europe",
    area: 30528,
    population: 11555997,
  },
  {
    id: "CAF",
    name: "Central African Republic",
    flag: "https://flagcdn.com/cf.svg",
    continent: "Africa",
    capital: "Bangui",
    subregion: "Middle Africa",
    area: 622984,
    population: 4829764,
  },
  {
    id: "HUN",
    name: "Hungary",
    flag: "https://flagcdn.com/hu.svg",
    continent: "Europe",
    capital: "Budapest",
    subregion: "Central Europe",
    area: 93028,
    population: 9749763,
  },
  {
    id: "MNG",
    name: "Mongolia",
    flag: "https://flagcdn.com/mn.svg",
    continent: "Asia",
    capital: "Ulan Bator",
    subregion: "Eastern Asia",
    area: 1564110,
    population: 3278292,
  },
  {
    id: "SAU",
    name: "Saudi Arabia",
    flag: "https://flagcdn.com/sa.svg",
    continent: "Asia",
    capital: "Riyadh",
    subregion: "Western Asia",
    area: 2149690,
    population: 34813867,
  },
  {
    id: "SWZ",
    name: "Eswatini",
    flag: "https://flagcdn.com/sz.svg",
    continent: "Africa",
    capital: "Mbabane",
    subregion: "Southern Africa",
    area: 17364,
    population: 1160164,
  },
  {
    id: "UGA",
    name: "Uganda",
    flag: "https://flagcdn.com/ug.svg",
    continent: "Africa",
    capital: "Kampala",
    subregion: "Eastern Africa",
    area: 241550,
    population: 45741000,
  },
  {
    id: "PRY",
    name: "Paraguay",
    flag: "https://flagcdn.com/py.svg",
    continent: "Americas",
    capital: "Asunción",
    subregion: "South America",
    area: 406752,
    population: 7132530,
  },
  {
    id: "CMR",
    name: "Cameroon",
    flag: "https://flagcdn.com/cm.svg",
    continent: "Africa",
    capital: "Yaoundé",
    subregion: "Middle Africa",
    area: 475442,
    population: 26545864,
  },
  {
    id: "FRA",
    name: "France",
    flag: "https://flagcdn.com/fr.svg",
    continent: "Europe",
    capital: "Paris",
    subregion: "Western Europe",
    area: 551695,
    population: 67391582,
  },
  {
    id: "TGO",
    name: "Togo",
    flag: "https://flagcdn.com/tg.svg",
    continent: "Africa",
    capital: "Lomé",
    subregion: "Western Africa",
    area: 56785,
    population: 8278737,
  },
  {
    id: "MUS",
    name: "Mauritius",
    flag: "https://flagcdn.com/mu.svg",
    continent: "Africa",
    capital: "Port Louis",
    subregion: "Eastern Africa",
    area: 2040,
    population: 1265740,
  },
  {
    id: "COK",
    name: "Cook Islands",
    flag: "https://flagcdn.com/ck.svg",
    continent: "Oceania",
    capital: "Avarua",
    subregion: "Polynesia",
    area: 236,
    population: 18100,
  },
  {
    id: "PLW",
    name: "Palau",
    flag: "https://flagcdn.com/pw.svg",
    continent: "Oceania",
    capital: "Ngerulmud",
    subregion: "Micronesia",
    area: 459,
    population: 18092,
  },
  {
    id: "NPL",
    name: "Nepal",
    flag: "https://flagcdn.com/np.svg",
    continent: "Asia",
    capital: "Kathmandu",
    subregion: "Southern Asia",
    area: 147181,
    population: 29136808,
  },
  {
    id: "NZL",
    name: "New Zealand",
    flag: "https://flagcdn.com/nz.svg",
    continent: "Oceania",
    capital: "Wellington",
    subregion: "Australia and New Zealand",
    area: 270467,
    population: 5084300,
  },
  {
    id: "PCN",
    name: "Pitcairn Islands",
    flag: "https://flagcdn.com/pn.svg",
    continent: "Oceania",
    capital: "Adamstown",
    subregion: "Polynesia",
    area: 47,
    population: 56,
  },
  {
    id: "SYC",
    name: "Seychelles",
    flag: "https://flagcdn.com/sc.svg",
    continent: "Africa",
    capital: "Victoria",
    subregion: "Eastern Africa",
    area: 452,
    population: 98462,
  },
  {
    id: "ARE",
    name: "United Arab Emirates",
    flag: "https://flagcdn.com/ae.svg",
    continent: "Asia",
    capital: "Abu Dhabi",
    subregion: "Western Asia",
    area: 83600,
    population: 9890400,
  },
  {
    id: "BLR",
    name: "Belarus",
    flag: "https://flagcdn.com/by.svg",
    continent: "Europe",
    capital: "Minsk",
    subregion: "Eastern Europe",
    area: 207600,
    population: 9398861,
  },
  {
    id: "DOM",
    name: "Dominican Republic",
    flag: "https://flagcdn.com/do.svg",
    continent: "Americas",
    capital: "Santo Domingo",
    subregion: "Caribbean",
    area: 48671,
    population: 10847904,
  },
  {
    id: "LBY",
    name: "Libya",
    flag: "https://flagcdn.com/ly.svg",
    continent: "Africa",
    capital: "Tripoli",
    subregion: "Northern Africa",
    area: 1759540,
    population: 6871287,
  },
  {
    id: "TKL",
    name: "Tokelau",
    flag: "https://flagcdn.com/tk.svg",
    continent: "Oceania",
    capital: "Fakaofo",
    subregion: "Polynesia",
    area: 12,
    population: 1411,
  },
  {
    id: "HRV",
    name: "Croatia",
    flag: "https://flagcdn.com/hr.svg",
    continent: "Europe",
    capital: "Zagreb",
    subregion: "Southeast Europe",
    area: 56594,
    population: 4047200,
  },
  {
    id: "PHL",
    name: "Philippines",
    flag: "https://flagcdn.com/ph.svg",
    continent: "Asia",
    capital: "Manila",
    subregion: "South-Eastern Asia",
    area: 342353,
    population: 109581085,
  },
  {
    id: "ALB",
    name: "Albania",
    flag: "https://flagcdn.com/al.svg",
    continent: "Europe",
    capital: "Tirana",
    subregion: "Southeast Europe",
    area: 28748,
    population: 2837743,
  },
  {
    id: "BVT",
    name: "Bouvet Island",
    flag: "https://flagcdn.com/bv.svg",
    continent: "Antarctic",
    capital: "None",
    subregion: null,
    area: 49,
    population: 0,
  },
  {
    id: "IDN",
    name: "Indonesia",
    flag: "https://flagcdn.com/id.svg",
    continent: "Asia",
    capital: "Jakarta",
    subregion: "South-Eastern Asia",
    area: 1904569,
    population: 273523621,
  },
  {
    id: "THA",
    name: "Thailand",
    flag: "https://flagcdn.com/th.svg",
    continent: "Asia",
    capital: "Bangkok",
    subregion: "South-Eastern Asia",
    area: 513120,
    population: 69799978,
  },
  {
    id: "LVA",
    name: "Latvia",
    flag: "https://flagcdn.com/lv.svg",
    continent: "Europe",
    capital: "Riga",
    subregion: "Northern Europe",
    area: 64559,
    population: 1901548,
  },
  {
    id: "ECU",
    name: "Ecuador",
    flag: "https://flagcdn.com/ec.svg",
    continent: "Americas",
    capital: "Quito",
    subregion: "South America",
    area: 276841,
    population: 17643060,
  },
  {
    id: "KEN",
    name: "Kenya",
    flag: "https://flagcdn.com/ke.svg",
    continent: "Africa",
    capital: "Nairobi",
    subregion: "Eastern Africa",
    area: 580367,
    population: 53771300,
  },
  {
    id: "LBR",
    name: "Liberia",
    flag: "https://flagcdn.com/lr.svg",
    continent: "Africa",
    capital: "Monrovia",
    subregion: "Western Africa",
    area: 111369,
    population: 5057677,
  },
  {
    id: "VGB",
    name: "British Virgin Islands",
    flag: "https://flagcdn.com/vg.svg",
    continent: "Americas",
    capital: "Road Town",
    subregion: "Caribbean",
    area: 151,
    population: 30237,
  },
  {
    id: "SMR",
    name: "San Marino",
    flag: "https://flagcdn.com/sm.svg",
    continent: "Europe",
    capital: "City of San Marino",
    subregion: "Southern Europe",
    area: 61,
    population: 33938,
  },
  {
    id: "IND",
    name: "India",
    flag: "https://flagcdn.com/in.svg",
    continent: "Asia",
    capital: "New Delhi",
    subregion: "Southern Asia",
    area: 3287590,
    population: 1380004385,
  },
  {
    id: "BHR",
    name: "Bahrain",
    flag: "https://flagcdn.com/bh.svg",
    continent: "Asia",
    capital: "Manama",
    subregion: "Western Asia",
    area: 765,
    population: 1701583,
  },
  {
    id: "MWI",
    name: "Malawi",
    flag: "https://flagcdn.com/mw.svg",
    continent: "Africa",
    capital: "Lilongwe",
    subregion: "Eastern Africa",
    area: 118484,
    population: 19129955,
  },
  {
    id: "ISL",
    name: "Iceland",
    flag: "https://flagcdn.com/is.svg",
    continent: "Europe",
    capital: "Reykjavik",
    subregion: "Northern Europe",
    area: 103000,
    population: 366425,
  },
  {
    id: "BRN",
    name: "Brunei",
    flag: "https://flagcdn.com/bn.svg",
    continent: "Asia",
    capital: "Bandar Seri Begawan",
    subregion: "South-Eastern Asia",
    area: 5765,
    population: 437483,
  },
  {
    id: "GUF",
    name: "French Guiana",
    flag: "https://flagcdn.com/gf.svg",
    continent: "Americas",
    capital: "Cayenne",
    subregion: "South America",
    area: 83534,
    population: 254541,
  },
  {
    id: "WSM",
    name: "Samoa",
    flag: "https://flagcdn.com/ws.svg",
    continent: "Oceania",
    capital: "Apia",
    subregion: "Polynesia",
    area: 2842,
    population: 198410,
  },
  {
    id: "GEO",
    name: "Georgia",
    flag: "https://flagcdn.com/ge.svg",
    continent: "Asia",
    capital: "Tbilisi",
    subregion: "Western Asia",
    area: 69700,
    population: 3714000,
  },
  {
    id: "BES",
    name: "Caribbean Netherlands",
    flag: "https://flagcdn.com/bq.svg",
    continent: "Americas",
    capital: "Kralendijk",
    subregion: "Caribbean",
    area: 328,
    population: 25987,
  },
  {
    id: "HMD",
    name: "Heard Island and McDonald Islands",
    flag: "https://flagcdn.com/hm.svg",
    continent: "Antarctic",
    capital: "None",
    subregion: null,
    area: 412,
    population: 0,
  },
  {
    id: "PNG",
    name: "Papua New Guinea",
    flag: "https://flagcdn.com/pg.svg",
    continent: "Oceania",
    capital: "Port Moresby",
    subregion: "Melanesia",
    area: 462840,
    population: 8947027,
  },
  {
    id: "GHA",
    name: "Ghana",
    flag: "https://flagcdn.com/gh.svg",
    continent: "Africa",
    capital: "Accra",
    subregion: "Western Africa",
    area: 238533,
    population: 31072945,
  },
  {
    id: "AFG",
    name: "Afghanistan",
    flag: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_the_Taliban.svg",
    continent: "Asia",
    capital: "Kabul",
    subregion: "Southern Asia",
    area: 652230,
    population: 40218234,
  },
  {
    id: "CRI",
    name: "Costa Rica",
    flag: "https://flagcdn.com/cr.svg",
    continent: "Americas",
    capital: "San José",
    subregion: "Central America",
    area: 51100,
    population: 5094114,
  },
  {
    id: "FJI",
    name: "Fiji",
    flag: "https://flagcdn.com/fj.svg",
    continent: "Oceania",
    capital: "Suva",
    subregion: "Melanesia",
    area: 18272,
    population: 896444,
  },
  {
    id: "KOR",
    name: "South Korea",
    flag: "https://flagcdn.com/kr.svg",
    continent: "Asia",
    capital: "Seoul",
    subregion: "Eastern Asia",
    area: 100210,
    population: 51780579,
  },
  {
    id: "TWN",
    name: "Taiwan",
    flag: "https://flagcdn.com/tw.svg",
    continent: "Asia",
    capital: "Taipei",
    subregion: "Eastern Asia",
    area: 36193,
    population: 23503349,
  },
  {
    id: "CZE",
    name: "Czechia",
    flag: "https://flagcdn.com/cz.svg",
    continent: "Europe",
    capital: "Prague",
    subregion: "Central Europe",
    area: 78865,
    population: 10698896,
  },
  {
    id: "NIC",
    name: "Nicaragua",
    flag: "https://flagcdn.com/ni.svg",
    continent: "Americas",
    capital: "Managua",
    subregion: "Central America",
    area: 130373,
    population: 6624554,
  },
  {
    id: "PRT",
    name: "Portugal",
    flag: "https://flagcdn.com/pt.svg",
    continent: "Europe",
    capital: "Lisbon",
    subregion: "Southern Europe",
    area: 92090,
    population: 10305564,
  },
  {
    id: "CHL",
    name: "Chile",
    flag: "https://flagcdn.com/cl.svg",
    continent: "Americas",
    capital: "Santiago",
    subregion: "South America",
    area: 756102,
    population: 19116209,
  },
  {
    id: "GMB",
    name: "Gambia",
    flag: "https://flagcdn.com/gm.svg",
    continent: "Africa",
    capital: "Banjul",
    subregion: "Western Africa",
    area: 10689,
    population: 2416664,
  },
  {
    id: "BLZ",
    name: "Belize",
    flag: "https://flagcdn.com/bz.svg",
    continent: "Americas",
    capital: "Belmopan",
    subregion: "Central America",
    area: 22966,
    population: 397621,
  },
  {
    id: "MDV",
    name: "Maldives",
    flag: "https://flagcdn.com/mv.svg",
    continent: "Asia",
    capital: "Malé",
    subregion: "Southern Asia",
    area: 300,
    population: 540542,
  },
  {
    id: "VUT",
    name: "Vanuatu",
    flag: "https://flagcdn.com/vu.svg",
    continent: "Oceania",
    capital: "Port Vila",
    subregion: "Melanesia",
    area: 12189,
    population: 307150,
  },
  {
    id: "MYS",
    name: "Malaysia",
    flag: "https://flagcdn.com/my.svg",
    continent: "Asia",
    capital: "Kuala Lumpur",
    subregion: "South-Eastern Asia",
    area: 330803,
    population: 32365998,
  },
  {
    id: "ATG",
    name: "Antigua and Barbuda",
    flag: "https://flagcdn.com/ag.svg",
    continent: "Americas",
    capital: "Saint John's",
    subregion: "Caribbean",
    area: 442,
    population: 97928,
  },
  {
    id: "IRN",
    name: "Iran",
    flag: "https://flagcdn.com/ir.svg",
    continent: "Asia",
    capital: "Tehran",
    subregion: "Southern Asia",
    area: 1648195,
    population: 83992953,
  },
  {
    id: "RUS",
    name: "Russia",
    flag: "https://flagcdn.com/ru.svg",
    continent: "Europe",
    capital: "Moscow",
    subregion: "Eastern Europe",
    area: 17098242,
    population: 144104080,
  },
  {
    id: "KIR",
    name: "Kiribati",
    flag: "https://flagcdn.com/ki.svg",
    continent: "Oceania",
    capital: "South Tarawa",
    subregion: "Micronesia",
    area: 811,
    population: 119446,
  },
  {
    id: "MTQ",
    name: "Martinique",
    flag: "https://flagcdn.com/mq.svg",
    continent: "Americas",
    capital: "Fort-de-France",
    subregion: "Caribbean",
    area: 1128,
    population: 378243,
  },
  {
    id: "BGD",
    name: "Bangladesh",
    flag: "https://flagcdn.com/bd.svg",
    continent: "Asia",
    capital: "Dhaka",
    subregion: "Southern Asia",
    area: 147570,
    population: 164689383,
  },
  {
    id: "ARM",
    name: "Armenia",
    flag: "https://flagcdn.com/am.svg",
    continent: "Asia",
    capital: "Yerevan",
    subregion: "Western Asia",
    area: 29743,
    population: 2963234,
  },
  {
    id: "MEX",
    name: "Mexico",
    flag: "https://flagcdn.com/mx.svg",
    continent: "Americas",
    capital: "Mexico City",
    subregion: "North America",
    area: 1964375,
    population: 128932753,
  },
  {
    id: "EST",
    name: "Estonia",
    flag: "https://flagcdn.com/ee.svg",
    continent: "Europe",
    capital: "Tallinn",
    subregion: "Northern Europe",
    area: 45227,
    population: 1331057,
  },
  {
    id: "OMN",
    name: "Oman",
    flag: "https://flagcdn.com/om.svg",
    continent: "Asia",
    capital: "Muscat",
    subregion: "Western Asia",
    area: 309500,
    population: 5106622,
  },
  {
    id: "USA",
    name: "United States",
    flag: "https://flagcdn.com/us.svg",
    continent: "Americas",
    capital: "Washington, D.C.",
    subregion: "North America",
    area: 9372610,
    population: 329484123,
  },
  {
    id: "LIE",
    name: "Liechtenstein",
    flag: "https://flagcdn.com/li.svg",
    continent: "Europe",
    capital: "Vaduz",
    subregion: "Western Europe",
    area: 160,
    population: 38137,
  },
  {
    id: "BHS",
    name: "Bahamas",
    flag: "https://flagcdn.com/bs.svg",
    continent: "Americas",
    capital: "Nassau",
    subregion: "Caribbean",
    area: 13943,
    population: 393248,
  },
  {
    id: "BEN",
    name: "Benin",
    flag: "https://flagcdn.com/bj.svg",
    continent: "Africa",
    capital: "Porto-Novo",
    subregion: "Western Africa",
    area: 112622,
    population: 12123198,
  },
  {
    id: "UNK",
    name: "Kosovo",
    flag: "https://flagcdn.com/xk.svg",
    continent: "Europe",
    capital: "Pristina",
    subregion: "Southeast Europe",
    area: 10908,
    population: 1775378,
  },
  {
    id: "TUV",
    name: "Tuvalu",
    flag: "https://flagcdn.com/tv.svg",
    continent: "Oceania",
    capital: "Funafuti",
    subregion: "Polynesia",
    area: 26,
    population: 11792,
  },
  {
    id: "FRO",
    name: "Faroe Islands",
    flag: "https://flagcdn.com/fo.svg",
    continent: "Europe",
    capital: "Tórshavn",
    subregion: "Northern Europe",
    area: 1393,
    population: 48865,
  },
  {
    id: "CYM",
    name: "Cayman Islands",
    flag: "https://flagcdn.com/ky.svg",
    continent: "Americas",
    capital: "George Town",
    subregion: "Caribbean",
    area: 264,
    population: 65720,
  },
  {
    id: "EGY",
    name: "Egypt",
    flag: "https://flagcdn.com/eg.svg",
    continent: "Africa",
    capital: "Cairo",
    subregion: "Northern Africa",
    area: 1002450,
    population: 102334403,
  },
  {
    id: "AZE",
    name: "Azerbaijan",
    flag: "https://flagcdn.com/az.svg",
    continent: "Asia",
    capital: "Baku",
    subregion: "Western Asia",
    area: 86600,
    population: 10110116,
  },
  {
    id: "AUS",
    name: "Australia",
    flag: "https://flagcdn.com/au.svg",
    continent: "Oceania",
    capital: "Canberra",
    subregion: "Australia and New Zealand",
    area: 7692024,
    population: 25687041,
  },
  {
    id: "IMN",
    name: "Isle of Man",
    flag: "https://flagcdn.com/im.svg",
    continent: "Europe",
    capital: "Douglas",
    subregion: "Northern Europe",
    area: 572,
    population: 85032,
  },
  {
    id: "IRL",
    name: "Ireland",
    flag: "https://flagcdn.com/ie.svg",
    continent: "Europe",
    capital: "Dublin",
    subregion: "Northern Europe",
    area: 70273,
    population: 4994724,
  },
  {
    id: "BRB",
    name: "Barbados",
    flag: "https://flagcdn.com/bb.svg",
    continent: "Americas",
    capital: "Bridgetown",
    subregion: "Caribbean",
    area: 430,
    population: 287371,
  },
  {
    id: "SLV",
    name: "El Salvador",
    flag: "https://flagcdn.com/sv.svg",
    continent: "Americas",
    capital: "San Salvador",
    subregion: "Central America",
    area: 21041,
    population: 6486201,
  },
  {
    id: "GTM",
    name: "Guatemala",
    flag: "https://flagcdn.com/gt.svg",
    continent: "Americas",
    capital: "Guatemala City",
    subregion: "Central America",
    area: 108889,
    population: 16858333,
  },
  {
    id: "JPN",
    name: "Japan",
    flag: "https://flagcdn.com/jp.svg",
    continent: "Asia",
    capital: "Tokyo",
    subregion: "Eastern Asia",
    area: 377930,
    population: 125836021,
  },
  {
    id: "VNM",
    name: "Vietnam",
    flag: "https://flagcdn.com/vn.svg",
    continent: "Asia",
    capital: "Hanoi",
    subregion: "South-Eastern Asia",
    area: 331212,
    population: 97338583,
  },
  {
    id: "MNP",
    name: "Northern Mariana Islands",
    flag: "https://flagcdn.com/mp.svg",
    continent: "Oceania",
    capital: "Saipan",
    subregion: "Micronesia",
    area: 464,
    population: 57557,
  },
  {
    id: "LTU",
    name: "Lithuania",
    flag: "https://flagcdn.com/lt.svg",
    continent: "Europe",
    capital: "Vilnius",
    subregion: "Northern Europe",
    area: 65300,
    population: 2794700,
  },
  {
    id: "LCA",
    name: "Saint Lucia",
    flag: "https://flagcdn.com/lc.svg",
    continent: "Americas",
    capital: "Castries",
    subregion: "Caribbean",
    area: 616,
    population: 183629,
  },
  {
    id: "HKG",
    name: "Hong Kong",
    flag: "https://flagcdn.com/hk.svg",
    continent: "Asia",
    capital: "City of Victoria",
    subregion: "Eastern Asia",
    area: 1104,
    population: 7500700,
  },
  {
    id: "AGO",
    name: "Angola",
    flag: "https://flagcdn.com/ao.svg",
    continent: "Africa",
    capital: "Luanda",
    subregion: "Middle Africa",
    area: 1246700,
    population: 32866268,
  },
  {
    id: "MOZ",
    name: "Mozambique",
    flag: "https://flagcdn.com/mz.svg",
    continent: "Africa",
    capital: "Maputo",
    subregion: "Eastern Africa",
    area: 801590,
    population: 31255435,
  },
  {
    id: "BWA",
    name: "Botswana",
    flag: "https://flagcdn.com/bw.svg",
    continent: "Africa",
    capital: "Gaborone",
    subregion: "Southern Africa",
    area: 582000,
    population: 2351625,
  },
  {
    id: "DEU",
    name: "Germany",
    flag: "https://flagcdn.com/de.svg",
    continent: "Europe",
    capital: "Berlin",
    subregion: "Western Europe",
    area: 357114,
    population: 83240525,
  },
  {
    id: "SYR",
    name: "Syria",
    flag: "https://flagcdn.com/sy.svg",
    continent: "Asia",
    capital: "Damascus",
    subregion: "Western Asia",
    area: 185180,
    population: 17500657,
  },
  {
    id: "MDA",
    name: "Moldova",
    flag: "https://flagcdn.com/md.svg",
    continent: "Europe",
    capital: "Chișinău",
    subregion: "Eastern Europe",
    area: 33846,
    population: 2617820,
  },
  {
    id: "SPM",
    name: "Saint Pierre and Miquelon",
    flag: "https://flagcdn.com/pm.svg",
    continent: "Americas",
    capital: "Saint-Pierre",
    subregion: "North America",
    area: 242,
    population: 6069,
  },
  {
    id: "GGY",
    name: "Guernsey",
    flag: "https://flagcdn.com/gg.svg",
    continent: "Europe",
    capital: "St. Peter Port",
    subregion: "Northern Europe",
    area: 78,
    population: 62999,
  },
  {
    id: "WLF",
    name: "Wallis and Futuna",
    flag: "https://flagcdn.com/wf.svg",
    continent: "Oceania",
    capital: "Mata-Utu",
    subregion: "Polynesia",
    area: 142,
    population: 11750,
  },
  {
    id: "POL",
    name: "Poland",
    flag: "https://flagcdn.com/pl.svg",
    continent: "Europe",
    capital: "Warsaw",
    subregion: "Central Europe",
    area: 312679,
    population: 37950802,
  },
  {
    id: "TTO",
    name: "Trinidad and Tobago",
    flag: "https://flagcdn.com/tt.svg",
    continent: "Americas",
    capital: "Port of Spain",
    subregion: "Caribbean",
    area: 5130,
    population: 1399491,
  },
  {
    id: "IOT",
    name: "British Indian Ocean Territory",
    flag: "https://flagcdn.com/io.svg",
    continent: "Africa",
    capital: "Diego Garcia",
    subregion: "Eastern Africa",
    area: 60,
    population: 3000,
  },
  {
    id: "MHL",
    name: "Marshall Islands",
    flag: "https://flagcdn.com/mh.svg",
    continent: "Oceania",
    capital: "Majuro",
    subregion: "Micronesia",
    area: 181,
    population: 59194,
  },
  {
    id: "AUT",
    name: "Austria",
    flag: "https://flagcdn.com/at.svg",
    continent: "Europe",
    capital: "Vienna",
    subregion: "Central Europe",
    area: 83871,
    population: 8917205,
  },
  {
    id: "KAZ",
    name: "Kazakhstan",
    flag: "https://flagcdn.com/kz.svg",
    continent: "Asia",
    capital: "Nur-Sultan",
    subregion: "Central Asia",
    area: 2724900,
    population: 18754440,
  },
  {
    id: "ABW",
    name: "Aruba",
    flag: "https://flagcdn.com/aw.svg",
    continent: "Americas",
    capital: "Oranjestad",
    subregion: "Caribbean",
    area: 180,
    population: 106766,
  },
  {
    id: "ZAF",
    name: "South Africa",
    flag: "https://flagcdn.com/za.svg",
    continent: "Africa",
    capital: "Cape Town",
    subregion: "Southern Africa",
    area: 1221037,
    population: 59308690,
  },
  {
    id: "DNK",
    name: "Denmark",
    flag: "https://flagcdn.com/dk.svg",
    continent: "Europe",
    capital: "Copenhagen",
    subregion: "Northern Europe",
    area: 43094,
    population: 5831404,
  },
  {
    id: "SUR",
    name: "Suriname",
    flag: "https://flagcdn.com/sr.svg",
    continent: "Americas",
    capital: "Paramaribo",
    subregion: "South America",
    area: 163820,
    population: 586634,
  },
  {
    id: "BMU",
    name: "Bermuda",
    flag: "https://flagcdn.com/bm.svg",
    continent: "Americas",
    capital: "Hamilton",
    subregion: "North America",
    area: 54,
    population: 63903,
  },
  {
    id: "MSR",
    name: "Montserrat",
    flag: "https://flagcdn.com/ms.svg",
    continent: "Americas",
    capital: "Plymouth",
    subregion: "Caribbean",
    area: 102,
    population: 4922,
  },
  {
    id: "CIV",
    name: "Ivory Coast",
    flag: "https://flagcdn.com/ci.svg",
    continent: "Africa",
    capital: "Yamoussoukro",
    subregion: "Western Africa",
    area: 322463,
    population: 26378275,
  },
  {
    id: "MRT",
    name: "Mauritania",
    flag: "https://flagcdn.com/mr.svg",
    continent: "Africa",
    capital: "Nouakchott",
    subregion: "Western Africa",
    area: 1030700,
    population: 4649660,
  },
  {
    id: "SLE",
    name: "Sierra Leone",
    flag: "https://flagcdn.com/sl.svg",
    continent: "Africa",
    capital: "Freetown",
    subregion: "Western Africa",
    area: 71740,
    population: 7976985,
  },
  {
    id: "GIN",
    name: "Guinea",
    flag: "https://flagcdn.com/gn.svg",
    continent: "Africa",
    capital: "Conakry",
    subregion: "Western Africa",
    area: 245857,
    population: 13132792,
  },
  {
    id: "PYF",
    name: "French Polynesia",
    flag: "https://flagcdn.com/pf.svg",
    continent: "Oceania",
    capital: "Papeetē",
    subregion: "Polynesia",
    area: 4167,
    population: 280904,
  },
  {
    id: "PAK",
    name: "Pakistan",
    flag: "https://flagcdn.com/pk.svg",
    continent: "Asia",
    capital: "Islamabad",
    subregion: "Southern Asia",
    area: 881912,
    population: 220892331,
  },
  {
    id: "UMI",
    name: "United States Minor Outlying Islands",
    flag: "https://flagcdn.com/um.svg",
    continent: "Americas",
    capital: "Washington DC",
    subregion: "North America",
    area: 34.2,
    population: 300,
  },
  {
    id: "LSO",
    name: "Lesotho",
    flag: "https://flagcdn.com/ls.svg",
    continent: "Africa",
    capital: "Maseru",
    subregion: "Southern Africa",
    area: 30355,
    population: 2142252,
  },
  {
    id: "SEN",
    name: "Senegal",
    flag: "https://flagcdn.com/sn.svg",
    continent: "Africa",
    capital: "Dakar",
    subregion: "Western Africa",
    area: 196722,
    population: 16743930,
  },
  {
    id: "TJK",
    name: "Tajikistan",
    flag: "https://flagcdn.com/tj.svg",
    continent: "Asia",
    capital: "Dushanbe",
    subregion: "Central Asia",
    area: 143100,
    population: 9537642,
  },
  {
    id: "CHE",
    name: "Switzerland",
    flag: "https://flagcdn.com/ch.svg",
    continent: "Europe",
    capital: "Bern",
    subregion: "Western Europe",
    area: 41284,
    population: 8654622,
  },
  {
    id: "ERI",
    name: "Eritrea",
    flag: "https://flagcdn.com/er.svg",
    continent: "Africa",
    capital: "Asmara",
    subregion: "Eastern Africa",
    area: 117600,
    population: 5352000,
  },
  {
    id: "ATF",
    name: "French Southern and Antarctic Lands",
    flag: "https://flagcdn.com/tf.svg",
    continent: "Antarctic",
    capital: "Port-aux-Français",
    subregion: null,
    area: 7747,
    population: 400,
  },
  {
    id: "JEY",
    name: "Jersey",
    flag: "https://flagcdn.com/je.svg",
    continent: "Europe",
    capital: "Saint Helier",
    subregion: "Northern Europe",
    area: 116,
    population: 100800,
  },
  {
    id: "KHM",
    name: "Cambodia",
    flag: "https://flagcdn.com/kh.svg",
    continent: "Asia",
    capital: "Phnom Penh",
    subregion: "South-Eastern Asia",
    area: 181035,
    population: 16718971,
  },
  {
    id: "VCT",
    name: "Saint Vincent and the Grenadines",
    flag: "https://flagcdn.com/vc.svg",
    continent: "Americas",
    capital: "Kingstown",
    subregion: "Caribbean",
    area: 389,
    population: 110947,
  },
  {
    id: "SXM",
    name: "Sint Maarten",
    flag: "https://flagcdn.com/sx.svg",
    continent: "Americas",
    capital: "Philipsburg",
    subregion: "Caribbean",
    area: 34,
    population: 40812,
  },
  {
    id: "VAT",
    name: "Vatican City",
    flag: "https://flagcdn.com/va.svg",
    continent: "Europe",
    capital: "Vatican City",
    subregion: "Southern Europe",
    area: 0.44,
    population: 451,
  },
  {
    id: "URY",
    name: "Uruguay",
    flag: "https://flagcdn.com/uy.svg",
    continent: "Americas",
    capital: "Montevideo",
    subregion: "South America",
    area: 181034,
    population: 3473727,
  },
  {
    id: "ESH",
    name: "Western Sahara",
    flag: "https://flagcdn.com/eh.svg",
    continent: "Africa",
    capital: "El Aaiún",
    subregion: "Northern Africa",
    area: 266000,
    population: 510713,
  },
  {
    id: "CPV",
    name: "Cape Verde",
    flag: "https://flagcdn.com/cv.svg",
    continent: "Africa",
    capital: "Praia",
    subregion: "Western Africa",
    area: 4033,
    population: 555988,
  },
  {
    id: "ITA",
    name: "Italy",
    flag: "https://flagcdn.com/it.svg",
    continent: "Europe",
    capital: "Rome",
    subregion: "Southern Europe",
    area: 301336,
    population: 59554023,
  },
  {
    id: "GBR",
    name: "United Kingdom",
    flag: "https://flagcdn.com/gb.svg",
    continent: "Europe",
    capital: "London",
    subregion: "Northern Europe",
    area: 242900,
    population: 67215293,
  },
  {
    id: "MAC",
    name: "Macau",
    flag: "https://flagcdn.com/mo.svg",
    continent: "Asia",
    capital: "None",
    subregion: "Eastern Asia",
    area: 30,
    population: 649342,
  },
  {
    id: "GUY",
    name: "Guyana",
    flag: "https://flagcdn.com/gy.svg",
    continent: "Americas",
    capital: "Georgetown",
    subregion: "South America",
    area: 214969,
    population: 786559,
  },
  {
    id: "NOR",
    name: "Norway",
    flag: "https://flagcdn.com/no.svg",
    continent: "Europe",
    capital: "Oslo",
    subregion: "Northern Europe",
    area: 323802,
    population: 5379475,
  },
  {
    id: "NCL",
    name: "New Caledonia",
    flag: "https://flagcdn.com/nc.svg",
    continent: "Oceania",
    capital: "Nouméa",
    subregion: "Melanesia",
    area: 18575,
    population: 271960,
  },
  {
    id: "SSD",
    name: "South Sudan",
    flag: "https://flagcdn.com/ss.svg",
    continent: "Africa",
    capital: "Juba",
    subregion: "Middle Africa",
    area: 619745,
    population: 11193729,
  },
  {
    id: "BFA",
    name: "Burkina Faso",
    flag: "https://flagcdn.com/bf.svg",
    continent: "Africa",
    capital: "Ouagadougou",
    subregion: "Western Africa",
    area: 272967,
    population: 20903278,
  },
  {
    id: "GLP",
    name: "Guadeloupe",
    flag: "https://flagcdn.com/gp.svg",
    continent: "Americas",
    capital: "Basse-Terre",
    subregion: "Caribbean",
    area: 1628,
    population: 400132,
  },
  {
    id: "LBN",
    name: "Lebanon",
    flag: "https://flagcdn.com/lb.svg",
    continent: "Asia",
    capital: "Beirut",
    subregion: "Western Asia",
    area: 10452,
    population: 6825442,
  },
  {
    id: "KNA",
    name: "Saint Kitts and Nevis",
    flag: "https://flagcdn.com/kn.svg",
    continent: "Americas",
    capital: "Basseterre",
    subregion: "Caribbean",
    area: 261,
    population: 53192,
  },
  {
    id: "KWT",
    name: "Kuwait",
    flag: "https://flagcdn.com/kw.svg",
    continent: "Asia",
    capital: "Kuwait City",
    subregion: "Western Asia",
    area: 17818,
    population: 4270563,
  },
  {
    id: "SGS",
    name: "South Georgia",
    flag: "https://flagcdn.com/gs.svg",
    continent: "Antarctic",
    capital: "King Edward Point",
    subregion: null,
    area: 3903,
    population: 30,
  },
  {
    id: "LUX",
    name: "Luxembourg",
    flag: "https://flagcdn.com/lu.svg",
    continent: "Europe",
    capital: "Luxembourg",
    subregion: "Western Europe",
    area: 2586,
    population: 632275,
  },
  {
    id: "MMR",
    name: "Myanmar",
    flag: "https://flagcdn.com/mm.svg",
    continent: "Asia",
    capital: "Naypyidaw",
    subregion: "South-Eastern Asia",
    area: 676578,
    population: 54409794,
  },
  {
    id: "ISR",
    name: "Israel",
    flag: "https://flagcdn.com/il.svg",
    continent: "Asia",
    capital: "Jerusalem",
    subregion: "Western Asia",
    area: 20770,
    population: 9216900,
  },
  {
    id: "TKM",
    name: "Turkmenistan",
    flag: "https://flagcdn.com/tm.svg",
    continent: "Asia",
    capital: "Ashgabat",
    subregion: "Central Asia",
    area: 488100,
    population: 6031187,
  },
  {
    id: "GRC",
    name: "Greece",
    flag: "https://flagcdn.com/gr.svg",
    continent: "Europe",
    capital: "Athens",
    subregion: "Southern Europe",
    area: 131990,
    population: 10715549,
  },
  {
    id: "MCO",
    name: "Monaco",
    flag: "https://flagcdn.com/mc.svg",
    continent: "Europe",
    capital: "Monaco",
    subregion: "Western Europe",
    area: 2.02,
    population: 39244,
  },
  {
    id: "VEN",
    name: "Venezuela",
    flag: "https://flagcdn.com/ve.svg",
    continent: "Americas",
    capital: "Caracas",
    subregion: "South America",
    area: 916445,
    population: 28435943,
  },
  {
    id: "COG",
    name: "Republic of the Congo",
    flag: "https://flagcdn.com/cg.svg",
    continent: "Africa",
    capital: "Brazzaville",
    subregion: "Middle Africa",
    area: 342000,
    population: 5657000,
  },
  {
    id: "ESP",
    name: "Spain",
    flag: "https://flagcdn.com/es.svg",
    continent: "Europe",
    capital: "Madrid",
    subregion: "Southern Europe",
    area: 505992,
    population: 47351567,
  },
  {
    id: "NFK",
    name: "Norfolk Island",
    flag: "https://flagcdn.com/nf.svg",
    continent: "Oceania",
    capital: "Kingston",
    subregion: "Australia and New Zealand",
    area: 36,
    population: 2302,
  },
  {
    id: "DMA",
    name: "Dominica",
    flag: "https://flagcdn.com/dm.svg",
    continent: "Americas",
    capital: "Roseau",
    subregion: "Caribbean",
    area: 751,
    population: 71991,
  },
  {
    id: "TUN",
    name: "Tunisia",
    flag: "https://flagcdn.com/tn.svg",
    continent: "Africa",
    capital: "Tunis",
    subregion: "Northern Africa",
    area: 163610,
    population: 11818618,
  },
  {
    id: "TUR",
    name: "Turkey",
    flag: "https://flagcdn.com/tr.svg",
    continent: "Asia",
    capital: "Ankara",
    subregion: "Western Asia",
    area: 783562,
    population: 84339067,
  },
  {
    id: "COL",
    name: "Colombia",
    flag: "https://flagcdn.com/co.svg",
    continent: "Americas",
    capital: "Bogotá",
    subregion: "South America",
    area: 1141748,
    population: 50882884,
  },
  {
    id: "COM",
    name: "Comoros",
    flag: "https://flagcdn.com/km.svg",
    continent: "Africa",
    capital: "Moroni",
    subregion: "Eastern Africa",
    area: 1862,
    population: 869595,
  },
  {
    id: "SLB",
    name: "Solomon Islands",
    flag: "https://flagcdn.com/sb.svg",
    continent: "Oceania",
    capital: "Honiara",
    subregion: "Melanesia",
    area: 28896,
    population: 686878,
  },
  {
    id: "BLM",
    name: "Saint Barthélemy",
    flag: "https://flagcdn.com/bl.svg",
    continent: "Americas",
    capital: "Gustavia",
    subregion: "Caribbean",
    area: 21,
    population: 4255,
  },
  {
    id: "UZB",
    name: "Uzbekistan",
    flag: "https://flagcdn.com/uz.svg",
    continent: "Asia",
    capital: "Tashkent",
    subregion: "Central Asia",
    area: 447400,
    population: 34232050,
  },
  {
    id: "PSE",
    name: "Palestine",
    flag: "https://flagcdn.com/ps.svg",
    continent: "Asia",
    capital: "Jerusalem",
    subregion: "Western Asia",
    area: 6220,
    population: 4803269,
  },
  {
    id: "ATA",
    name: "Antarctica",
    flag: "https://flagcdn.com/aq.svg",
    continent: "Antarctic",
    capital: "None",
    subregion: null,
    area: 14000000,
    population: 1000,
  },
  {
    id: "CUB",
    name: "Cuba",
    flag: "https://flagcdn.com/cu.svg",
    continent: "Americas",
    capital: "Havana",
    subregion: "Caribbean",
    area: 109884,
    population: 11326616,
  },
  {
    id: "GAB",
    name: "Gabon",
    flag: "https://flagcdn.com/ga.svg",
    continent: "Africa",
    capital: "Libreville",
    subregion: "Middle Africa",
    area: 267668,
    population: 2225728,
  },
  {
    id: "KGZ",
    name: "Kyrgyzstan",
    flag: "https://flagcdn.com/kg.svg",
    continent: "Asia",
    capital: "Bishkek",
    subregion: "Central Asia",
    area: 199951,
    population: 6591600,
  },
  {
    id: "FSM",
    name: "Micronesia",
    flag: "https://flagcdn.com/fm.svg",
    continent: "Oceania",
    capital: "Palikir",
    subregion: "Micronesia",
    area: 702,
    population: 115021,
  },
  {
    id: "SWE",
    name: "Sweden",
    flag: "https://flagcdn.com/se.svg",
    continent: "Europe",
    capital: "Stockholm",
    subregion: "Northern Europe",
    area: 450295,
    population: 10353442,
  },
  {
    id: "MAF",
    name: "Saint Martin",
    flag: "https://flagcdn.com/mf.svg",
    continent: "Americas",
    capital: "Marigot",
    subregion: "Caribbean",
    area: 53,
    population: 38659,
  },
  {
    id: "SVK",
    name: "Slovakia",
    flag: "https://flagcdn.com/sk.svg",
    continent: "Europe",
    capital: "Bratislava",
    subregion: "Central Europe",
    area: 49037,
    population: 5458827,
  },
  {
    id: "COD",
    name: "DR Congo",
    flag: "https://flagcdn.com/cd.svg",
    continent: "Africa",
    capital: "Kinshasa",
    subregion: "Middle Africa",
    area: 2344858,
    population: 108407721,
  },
  {
    id: "MNE",
    name: "Montenegro",
    flag: "https://flagcdn.com/me.svg",
    continent: "Europe",
    capital: "Podgorica",
    subregion: "Southeast Europe",
    area: 13812,
    population: 621718,
  },
  {
    id: "GIB",
    name: "Gibraltar",
    flag: "https://flagcdn.com/gi.svg",
    continent: "Europe",
    capital: "Gibraltar",
    subregion: "Southern Europe",
    area: 6,
    population: 33691,
  },
  {
    id: "SOM",
    name: "Somalia",
    flag: "https://flagcdn.com/so.svg",
    continent: "Africa",
    capital: "Mogadishu",
    subregion: "Eastern Africa",
    area: 637657,
    population: 15893219,
  },
  {
    id: "LKA",
    name: "Sri Lanka",
    flag: "https://flagcdn.com/lk.svg",
    continent: "Asia",
    capital: "Sri Jayawardenepura Kotte",
    subregion: "Southern Asia",
    area: 65610,
    population: 21919000,
  },
  {
    id: "CYP",
    name: "Cyprus",
    flag: "https://flagcdn.com/cy.svg",
    continent: "Europe",
    capital: "Nicosia",
    subregion: "Southern Europe",
    area: 9251,
    population: 1207361,
  },
  {
    id: "LAO",
    name: "Laos",
    flag: "https://flagcdn.com/la.svg",
    continent: "Asia",
    capital: "Vientiane",
    subregion: "South-Eastern Asia",
    area: 236800,
    population: 7275556,
  },
  {
    id: "MAR",
    name: "Morocco",
    flag: "https://flagcdn.com/ma.svg",
    continent: "Africa",
    capital: "Rabat",
    subregion: "Northern Africa",
    area: 446550,
    population: 36910558,
  },
  {
    id: "TLS",
    name: "Timor-Leste",
    flag: "https://flagcdn.com/tl.svg",
    continent: "Asia",
    capital: "Dili",
    subregion: "South-Eastern Asia",
    area: 14874,
    population: 1318442,
  },
  {
    id: "YEM",
    name: "Yemen",
    flag: "https://flagcdn.com/ye.svg",
    continent: "Asia",
    capital: "Sana'a",
    subregion: "Western Asia",
    area: 527968,
    population: 29825968,
  },
  {
    id: "FLK",
    name: "Falkland Islands",
    flag: "https://flagcdn.com/fk.svg",
    continent: "Americas",
    capital: "Stanley",
    subregion: "South America",
    area: 12173,
    population: 2563,
  },
  {
    id: "GNQ",
    name: "Equatorial Guinea",
    flag: "https://flagcdn.com/gq.svg",
    continent: "Africa",
    capital: "Malabo",
    subregion: "Middle Africa",
    area: 28051,
    population: 1402985,
  },
  {
    id: "DZA",
    name: "Algeria",
    flag: "https://flagcdn.com/dz.svg",
    continent: "Africa",
    capital: "Algiers",
    subregion: "Northern Africa",
    area: 2381741,
    population: 44700000,
  },
  {
    id: "ZMB",
    name: "Zambia",
    flag: "https://flagcdn.com/zm.svg",
    continent: "Africa",
    capital: "Lusaka",
    subregion: "Eastern Africa",
    area: 752612,
    population: 18383956,
  },
  {
    id: "SRB",
    name: "Serbia",
    flag: "https://flagcdn.com/rs.svg",
    continent: "Europe",
    capital: "Belgrade",
    subregion: "Southeast Europe",
    area: 88361,
    population: 6908224,
  },
  {
    id: "AND",
    name: "Andorra",
    flag: "https://flagcdn.com/ad.svg",
    continent: "Europe",
    capital: "Andorra la Vella",
    subregion: "Southern Europe",
    area: 468,
    population: 77265,
  },
  {
    id: "STP",
    name: "São Tomé and Príncipe",
    flag: "https://flagcdn.com/st.svg",
    continent: "Africa",
    capital: "São Tomé",
    subregion: "Middle Africa",
    area: 964,
    population: 219161,
  },
  {
    id: "DJI",
    name: "Djibouti",
    flag: "https://flagcdn.com/dj.svg",
    continent: "Africa",
    capital: "Djibouti",
    subregion: "Eastern Africa",
    area: 23200,
    population: 988002,
  },
  {
    id: "BGR",
    name: "Bulgaria",
    flag: "https://flagcdn.com/bg.svg",
    continent: "Europe",
    capital: "Sofia",
    subregion: "Southeast Europe",
    area: 110879,
    population: 6927288,
  },
  {
    id: "VIR",
    name: "United States Virgin Islands",
    flag: "https://flagcdn.com/vi.svg",
    continent: "Americas",
    capital: "Charlotte Amalie",
    subregion: "Caribbean",
    area: 347,
    population: 106290,
  },
  {
    id: "ARG",
    name: "Argentina",
    flag: "https://flagcdn.com/ar.svg",
    continent: "Americas",
    capital: "Buenos Aires",
    subregion: "South America",
    area: 2780400,
    population: 45376763,
  },
  {
    id: "NGA",
    name: "Nigeria",
    flag: "https://flagcdn.com/ng.svg",
    continent: "Africa",
    capital: "Abuja",
    subregion: "Western Africa",
    area: 923768,
    population: 206139587,
  },
  {
    id: "RWA",
    name: "Rwanda",
    flag: "https://flagcdn.com/rw.svg",
    continent: "Africa",
    capital: "Kigali",
    subregion: "Eastern Africa",
    area: 26338,
    population: 12952209,
  },
  {
    id: "SHN",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    flag: "https://flagcdn.com/sh.svg",
    continent: "Africa",
    capital: "Jamestown",
    subregion: "Western Africa",
    area: 394,
    population: 53192,
  },
  {
    id: "CAN",
    name: "Canada",
    flag: "https://flagcdn.com/ca.svg",
    continent: "Americas",
    capital: "Ottawa",
    subregion: "North America",
    area: 9984670,
    population: 38005238,
  },
  {
    id: "PRK",
    name: "North Korea",
    flag: "https://flagcdn.com/kp.svg",
    continent: "Asia",
    capital: "Pyongyang",
    subregion: "Eastern Asia",
    area: 120538,
    population: 25778815,
  },
  {
    id: "ALA",
    name: "Åland Islands",
    flag: "https://flagcdn.com/ax.svg",
    continent: "Europe",
    capital: "Mariehamn",
    subregion: "Northern Europe",
    area: 1580,
    population: 29458,
  },
  {
    id: "MKD",
    name: "North Macedonia",
    flag: "https://flagcdn.com/mk.svg",
    continent: "Europe",
    capital: "Skopje",
    subregion: "Southeast Europe",
    area: 25713,
    population: 2077132,
  },
  {
    id: "NLD",
    name: "Netherlands",
    flag: "https://flagcdn.com/nl.svg",
    continent: "Europe",
    capital: "Amsterdam",
    subregion: "Western Europe",
    area: 41850,
    population: 16655799,
  },
  {
    id: "NER",
    name: "Niger",
    flag: "https://flagcdn.com/ne.svg",
    continent: "Africa",
    capital: "Niamey",
    subregion: "Western Africa",
    area: 1267000,
    population: 24206636,
  },
  {
    id: "SGP",
    name: "Singapore",
    flag: "https://flagcdn.com/sg.svg",
    continent: "Asia",
    capital: "Singapore",
    subregion: "South-Eastern Asia",
    area: 710,
    population: 5685807,
  },
  {
    id: "TCD",
    name: "Chad",
    flag: "https://flagcdn.com/td.svg",
    continent: "Africa",
    capital: "N'Djamena",
    subregion: "Middle Africa",
    area: 1284000,
    population: 16425859,
  },
  {
    id: "CUW",
    name: "Curaçao",
    flag: "https://flagcdn.com/cw.svg",
    continent: "Americas",
    capital: "Willemstad",
    subregion: "Caribbean",
    area: 444,
    population: 155014,
  },
  {
    id: "NIU",
    name: "Niue",
    flag: "https://flagcdn.com/nu.svg",
    continent: "Oceania",
    capital: "Alofi",
    subregion: "Polynesia",
    area: 260,
    population: 1470,
  },
  {
    id: "GNB",
    name: "Guinea-Bissau",
    flag: "https://flagcdn.com/gw.svg",
    continent: "Africa",
    capital: "Bissau",
    subregion: "Western Africa",
    area: 36125,
    population: 1967998,
  },
  {
    id: "NRU",
    name: "Nauru",
    flag: "https://flagcdn.com/nr.svg",
    continent: "Oceania",
    capital: "Yaren",
    subregion: "Micronesia",
    area: 21,
    population: 10834,
  },
  {
    id: "ZWE",
    name: "Zimbabwe",
    flag: "https://flagcdn.com/zw.svg",
    continent: "Africa",
    capital: "Harare",
    subregion: "Southern Africa",
    area: 390757,
    population: 14862927,
  },
  {
    id: "CHN",
    name: "China",
    flag: "https://flagcdn.com/cn.svg",
    continent: "Asia",
    capital: "Beijing",
    subregion: "Eastern Asia",
    area: 9706961,
    population: 1402112000,
  },
  {
    id: "CXR",
    name: "Christmas Island",
    flag: "https://flagcdn.com/cx.svg",
    continent: "Oceania",
    capital: "Flying Fish Cove",
    subregion: "Australia and New Zealand",
    area: 135,
    population: 2072,
  },
  {
    id: "PRI",
    name: "Puerto Rico",
    flag: "https://flagcdn.com/pr.svg",
    continent: "Americas",
    capital: "San Juan",
    subregion: "Caribbean",
    area: 8870,
    population: 3194034,
  },
  {
    id: "ETH",
    name: "Ethiopia",
    flag: "https://flagcdn.com/et.svg",
    continent: "Africa",
    capital: "Addis Ababa",
    subregion: "Eastern Africa",
    area: 1104300,
    population: 114963583,
  },
  {
    id: "GRD",
    name: "Grenada",
    flag: "https://flagcdn.com/gd.svg",
    continent: "Americas",
    capital: "St. George's",
    subregion: "Caribbean",
    area: 344,
    population: 112519,
  },
  {
    id: "FIN",
    name: "Finland",
    flag: "https://flagcdn.com/fi.svg",
    continent: "Europe",
    capital: "Helsinki",
    subregion: "Northern Europe",
    area: 338424,
    population: 5530719,
  },
  {
    id: "TCA",
    name: "Turks and Caicos Islands",
    flag: "https://flagcdn.com/tc.svg",
    continent: "Americas",
    capital: "Cockburn Town",
    subregion: "Caribbean",
    area: 948,
    population: 38718,
  },
  {
    id: "BDI",
    name: "Burundi",
    flag: "https://flagcdn.com/bi.svg",
    continent: "Africa",
    capital: "Gitega",
    subregion: "Eastern Africa",
    area: 27834,
    population: 11890781,
  },
  {
    id: "GUM",
    name: "Guam",
    flag: "https://flagcdn.com/gu.svg",
    continent: "Oceania",
    capital: "Hagåtña",
    subregion: "Micronesia",
    area: 549,
    population: 168783,
  },
  {
    id: "JOR",
    name: "Jordan",
    flag: "https://flagcdn.com/jo.svg",
    continent: "Asia",
    capital: "Amman",
    subregion: "Western Asia",
    area: 89342,
    population: 10203140,
  },
  {
    id: "MLI",
    name: "Mali",
    flag: "https://flagcdn.com/ml.svg",
    continent: "Africa",
    capital: "Bamako",
    subregion: "Western Africa",
    area: 1240192,
    population: 20250834,
  },
  {
    id: "UKR",
    name: "Ukraine",
    flag: "https://flagcdn.com/ua.svg",
    continent: "Europe",
    capital: "Kyiv",
    subregion: "Eastern Europe",
    area: 603500,
    population: 44134693,
  },
  {
    id: "REU",
    name: "Réunion",
    flag: "https://flagcdn.com/re.svg",
    continent: "Africa",
    capital: "Saint-Denis",
    subregion: "Eastern Africa",
    area: 2511,
    population: 840974,
  },
  {
    id: "SJM",
    name: "Svalbard and Jan Mayen",
    flag: "https://flagcdn.com/sj.svg",
    continent: "Europe",
    capital: "Longyearbyen",
    subregion: "Northern Europe",
    area: -1,
    population: 2562,
  },
  {
    id: "CCK",
    name: "Cocos (Keeling) Islands",
    flag: "https://flagcdn.com/cc.svg",
    continent: "Oceania",
    capital: "West Island",
    subregion: "Australia and New Zealand",
    area: 14,
    population: 544,
  },
  {
    id: "TZA",
    name: "Tanzania",
    flag: "https://flagcdn.com/tz.svg",
    continent: "Africa",
    capital: "Dodoma",
    subregion: "Eastern Africa",
    area: 945087,
    population: 59734213,
  },
  {
    id: "QAT",
    name: "Qatar",
    flag: "https://flagcdn.com/qa.svg",
    continent: "Asia",
    capital: "Doha",
    subregion: "Western Asia",
    area: 11586,
    population: 2881060,
  },
  {
    id: "BRA",
    name: "Brazil",
    flag: "https://flagcdn.com/br.svg",
    continent: "Americas",
    capital: "Brasília",
    subregion: "South America",
    area: 8515767,
    population: 212559409,
  },
  {
    id: "SDN",
    name: "Sudan",
    flag: "https://flagcdn.com/sd.svg",
    continent: "Africa",
    capital: "Khartoum",
    subregion: "Northern Africa",
    area: 1886068,
    population: 43849269,
  },
  {
    id: "ROU",
    name: "Romania",
    flag: "https://flagcdn.com/ro.svg",
    continent: "Europe",
    capital: "Bucharest",
    subregion: "Southeast Europe",
    area: 238391,
    population: 19286123,
  },
  {
    id: "AIA",
    name: "Anguilla",
    flag: "https://flagcdn.com/ai.svg",
    continent: "Americas",
    capital: "The Valley",
    subregion: "Caribbean",
    area: 91,
    population: 13452,
  },
  {
    id: "IRQ",
    name: "Iraq",
    flag: "https://flagcdn.com/iq.svg",
    continent: "Asia",
    capital: "Baghdad",
    subregion: "Western Asia",
    area: 438317,
    population: 40222503,
  },
  {
    id: "BTN",
    name: "Bhutan",
    flag: "https://flagcdn.com/bt.svg",
    continent: "Asia",
    capital: "Thimphu",
    subregion: "Southern Asia",
    area: 38394,
    population: 771612,
  },
  {
    id: "HND",
    name: "Honduras",
    flag: "https://flagcdn.com/hn.svg",
    continent: "Americas",
    capital: "Tegucigalpa",
    subregion: "Central America",
    area: 112492,
    population: 9904608,
  },
  {
    id: "NAM",
    name: "Namibia",
    flag: "https://flagcdn.com/na.svg",
    continent: "Africa",
    capital: "Windhoek",
    subregion: "Southern Africa",
    area: 825615,
    population: 2540916,
  },
  {
    id: "SVN",
    name: "Slovenia",
    flag: "https://flagcdn.com/si.svg",
    continent: "Europe",
    capital: "Ljubljana",
    subregion: "Central Europe",
    area: 20273,
    population: 2100126,
  },
  {
    id: "HTI",
    name: "Haiti",
    flag: "https://flagcdn.com/ht.svg",
    continent: "Americas",
    capital: "Port-au-Prince",
    subregion: "Caribbean",
    area: 27750,
    population: 11402533,
  },
  {
    id: "BIH",
    name: "Bosnia and Herzegovina",
    flag: "https://flagcdn.com/ba.svg",
    continent: "Europe",
    capital: "Sarajevo",
    subregion: "Southeast Europe",
    area: 51209,
    population: 3280815,
  },
  {
    id: "GRL",
    name: "Greenland",
    flag: "https://flagcdn.com/gl.svg",
    continent: "Americas",
    capital: "Nuuk",
    subregion: "North America",
    area: 2166086,
    population: 56367,
  },
  {
    id: "JAM",
    name: "Jamaica",
    flag: "https://flagcdn.com/jm.svg",
    continent: "Americas",
    capital: "Kingston",
    subregion: "Caribbean",
    area: 10991,
    population: 2961161,
  },
  {
    id: "MLT",
    name: "Malta",
    flag: "https://flagcdn.com/mt.svg",
    continent: "Europe",
    capital: "Valletta",
    subregion: "Southern Europe",
    area: 316,
    population: 525285,
  },
  {
    id: "BOL",
    name: "Bolivia",
    flag: "https://flagcdn.com/bo.svg",
    continent: "Americas",
    capital: "Sucre",
    subregion: "South America",
    area: 1098581,
    population: 11673029,
  },
];

export default countries;
