export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const GET_COUNTRY_BY_ID = "GET_COUNTRY_BY_ID";

export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const SET_SELECTED_CONTINENT = "SET_SELECTED_CONTINENT";
export const SET_SELECTED_ACTIVITY = "SET_SELECTED_ACTIVITY";

export const SET_SORT_OPTION = "SET_SORT_OPTION";

export const POST_ACTIVITY = "POST_ACTIVITY";

export const SET_PAGE = "SET_PAGE";
